services:
  - type: web
    name: llm-efficiency-backend
    env: python
    rootDir: Backend/production

    buildCommand: pip install -r requirements.txt
    startCommand: python api.py

    plan: free
