services:
  - type: web
    name: llm-efficiency-backend
    env: python
    plan: free

    rootDir: Backend/production

    buildCommand: |
      pip install -r requirements.txt

    startCommand: python api.py

    pythonVersion: 3.12.10

    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
